release

diff --git a/.github/workflows/ehtml.yml b/.github/workflows/ehtml.yml
--- a/.github/workflows/ehtml.yml
+++ b/.github/workflows/ehtml.yml
@@ -1,29 +1,53 @@
+name: EHTML CI
+
 on:
   push:
-    # Sequence of patterns matched against refs/tags
-    tags:
-      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
-
-name: Create EHTML Release
+    branches: [ "master" ]
+  pull_request:
+    branches: [ "master" ]
 
 jobs:
   build:
-    name: Create Release
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version: [16.x]
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: Create Release
-        id: create_release
+    - uses: actions/checkout@v3
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v3
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+    - run: npm ci
+    - run: npm run lint
+    - run: npm run build
+
+  release:
+    runs-on: ubuntu-latest
+    needs: build  # Ensure that the 'build' job completes before running the release job
+    steps:
+      - name: Check Commit Message
+        run: |
+          last_commit_message=$(git log -1 --pretty=%B)
+          if [[ $last_commit_message =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Release will be triggered for commit: $last_commit_message"
+          else
+            echo "No release will be triggered for commit: $last_commit_message"
+            exit 78  # This will skip the job without failing
+          fi
+      - uses: actions/checkout@v3
+      - name: Create GitHub Release
         uses: actions/create-release@v1
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ github.ref }}
           release_name: Release ${{ github.ref }}
           body: |
             Changes in this Release
-            ${{ steps.extract_messages.outputs.commits }}
-          files: ehtml.bundle.min.js
+            - First Change
+            - Second Change
+          files: 'ehtml.bundle.min.js'
           draft: false
           prerelease: false
